import {
  TeamMemberResource,
  CategoryMeta,
  CalendarEventCategory,
} from '@/types/calendarTypes';

export const CATEGORY_CONFIG: Record<CalendarEventCategory, CategoryMeta> = {
  team_task: {
    id: 'team_task',
    label: 'Team Tasks & Follow-ups',
    pillLabel: 'Team Task',
    bgClass: 'bg-sky-50/90',
    borderClass: 'border-sky-300/80',
    textClass: 'text-[#0284c7]',
    dotColor: '#0284c7',
    badgeClass: 'bg-sky-100 text-[#0284c7] border-sky-300/80',
  },
  client_meeting: {
    id: 'client_meeting',
    label: 'Client Visits & Meetings',
    pillLabel: 'Client Visit',
    bgClass: 'bg-purple-50/90',
    borderClass: 'border-purple-300/80',
    textClass: 'text-purple-800',
    dotColor: '#7c3aed',
    badgeClass: 'bg-purple-100 text-purple-900 border-purple-300/80',
  },
  client_visit: {
    id: 'client_visit',
    label: 'Client Visits & Meetings',
    pillLabel: 'Client Visit',
    bgClass: 'bg-purple-50/90',
    borderClass: 'border-purple-300/80',
    textClass: 'text-purple-800',
    dotColor: '#7c3aed',
    badgeClass: 'bg-purple-100 text-purple-900 border-purple-300/80',
  },
  project_op: {
    id: 'project_op',
    label: 'Project Operations',
    pillLabel: 'Project Op',
    bgClass: 'bg-amber-50/90',
    borderClass: 'border-amber-300/80',
    textClass: 'text-amber-800',
    dotColor: '#d97706',
    badgeClass: 'bg-amber-100 text-amber-900 border-amber-300/80',
  },
  permit_filing: {
    id: 'permit_filing',
    label: 'Permits & City Filings',
    pillLabel: 'Permit Filing',
    bgClass: 'bg-emerald-50/90',
    borderClass: 'border-emerald-300/80',
    textClass: 'text-emerald-800',
    dotColor: '#059669',
    badgeClass: 'bg-emerald-100 text-emerald-900 border-emerald-300/80',
  },
  city_permit: {
    id: 'city_permit',
    label: 'Permits & City Filings',
    pillLabel: 'City Permit',
    bgClass: 'bg-emerald-50/90',
    borderClass: 'border-emerald-300/80',
    textClass: 'text-emerald-800',
    dotColor: '#059669',
    badgeClass: 'bg-emerald-100 text-emerald-900 border-emerald-300/80',
  },
  roof_install: {
    id: 'roof_install',
    label: 'Roof Installations',
    pillLabel: 'Install',
    bgClass: 'bg-sky-50/90',
    borderClass: 'border-sky-300/80',
    textClass: 'text-[#0284c7]',
    dotColor: '#0284c7',
    badgeClass: 'bg-sky-100 text-[#0284c7] border-sky-300/80',
  },
  boom_delivery: {
    id: 'boom_delivery',
    label: 'Boom Deliveries & Staging',
    pillLabel: 'Delivery',
    bgClass: 'bg-amber-50/90',
    borderClass: 'border-amber-300/80',
    textClass: 'text-amber-800',
    dotColor: '#d97706',
    badgeClass: 'bg-amber-100 text-amber-900 border-amber-300/80',
  },
  roof_inspection: {
    id: 'roof_inspection',
    label: 'Roof Inspections',
    pillLabel: 'Inspection',
    bgClass: 'bg-purple-50/90',
    borderClass: 'border-purple-300/80',
    textClass: 'text-purple-800',
    dotColor: '#7c3aed',
    badgeClass: 'bg-purple-100 text-purple-900 border-purple-300/80',
  },
  reminder: {
    id: 'reminder',
    label: 'Reminders & Check-ins',
    pillLabel: 'Reminder',
    bgClass: 'bg-rose-50/90',
    borderClass: 'border-rose-300/80',
    textClass: 'text-rose-800',
    dotColor: '#f43f5e',
    badgeClass: 'bg-rose-100 text-rose-900 border-rose-300/80',
  },
  warranty_audit: {
    id: 'warranty_audit',
    label: 'Warranty Check-ins',
    pillLabel: 'Warranty',
    bgClass: 'bg-teal-50/90',
    borderClass: 'border-teal-300/80',
    textClass: 'text-teal-800',
    dotColor: '#0d9488',
    badgeClass: 'bg-teal-100 text-teal-900 border-teal-300/80',
  },
  warranty_checkin: {
    id: 'warranty_checkin',
    label: 'Warranty Check-ins',
    pillLabel: 'Warranty',
    bgClass: 'bg-teal-50/90',
    borderClass: 'border-teal-300/80',
    textClass: 'text-teal-800',
    dotColor: '#0d9488',
    badgeClass: 'bg-teal-100 text-teal-900 border-teal-300/80',
  },
  manual_task: {
    id: 'manual_task',
    label: 'Team Tasks',
    pillLabel: 'Team Task',
    bgClass: 'bg-sky-50/90',
    borderClass: 'border-sky-300/80',
    textClass: 'text-[#0284c7]',
    dotColor: '#0284c7',
    badgeClass: 'bg-sky-100 text-[#0284c7] border-sky-300/80',
  },
};

export const CREW_RESOURCES: TeamMemberResource[] = [];
