"""Generate ``ruff-baseline.toml``: per-file ignores for the rule codes each file violates today.

Ratchet semantics: the baseline lists *only* what is currently violated. New files get no
ignores and must be clean; fixing a violation and re-running this script shrinks the baseline.

Usage (from ``backend/``)::

    python scripts/gen_ruff_baseline.py

The script first blanks the baseline so the measurement is not influenced by the old one.
"""
from __future__ import annotations

import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
BASELINE_PATH = BACKEND_DIR / "ruff-baseline.toml"
TARGET = "app"

HEADER = (
    "# GENERATED by scripts/gen_ruff_baseline.py - do not edit by hand.\n"
    "# Legacy lint debt, per file. This list may only shrink: fix violations, then regenerate.\n"
)


def group_violations(violations: list[dict], root: Path = BACKEND_DIR) -> dict[str, list[str]]:
    """Map relative posix file path -> sorted unique rule codes."""
    grouped: dict[str, set[str]] = defaultdict(set)
    for v in violations:
        code = v.get("code")
        if not code:  # syntax errors etc. have no code and must not be baselined
            continue
        rel = Path(v["filename"]).resolve().relative_to(root).as_posix()
        grouped[rel].add(code)
    return {path: sorted(codes) for path, codes in sorted(grouped.items())}


def render_baseline(grouped: dict[str, list[str]]) -> str:
    lines = [HEADER, "[lint.extend-per-file-ignores]"]
    for path, codes in grouped.items():
        rendered = ", ".join(f'"{c}"' for c in codes)
        lines.append(f'"{path}" = [{rendered}]')
    return "\n".join(lines) + "\n"


def run_ruff() -> list[dict]:
    proc = subprocess.run(  # noqa: S603
        [sys.executable, "-m", "ruff", "check", TARGET, "--output-format", "json", "--no-fix", "--exit-zero"],
        cwd=BACKEND_DIR,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise SystemExit(f"ruff failed:\n{proc.stderr}")
    return json.loads(proc.stdout or "[]")


def main() -> None:
    previous = BASELINE_PATH.read_text(encoding="utf-8") if BASELINE_PATH.exists() else None
    BASELINE_PATH.write_text(HEADER + "[lint.extend-per-file-ignores]\n", encoding="utf-8")
    try:
        grouped = group_violations(run_ruff())
    except BaseException:
        if previous is not None:
            BASELINE_PATH.write_text(previous, encoding="utf-8")
        raise
    BASELINE_PATH.write_text(render_baseline(grouped), encoding="utf-8")
    total = sum(len(codes) for codes in grouped.values())
    print(f"Wrote {BASELINE_PATH.name}: {len(grouped)} files, {total} (file, rule) entries")


if __name__ == "__main__":
    main()
