from app.core.logger import get_logger
import os
import sys
import asyncio
from typing import Dict, Any, Optional
from datetime import datetime
from jinja2 import Environment, FileSystemLoader
from concurrent.futures import ThreadPoolExecutor
from playwright.sync_api import sync_playwright

logger = get_logger(__name__)

_PDF_SEMAPHORE: Optional[asyncio.Semaphore] = None
_PDF_EXECUTOR = ThreadPoolExecutor(max_workers=2, thread_name_prefix="pdf_worker")

def _get_pdf_semaphore() -> asyncio.Semaphore:
    global _PDF_SEMAPHORE
    if _PDF_SEMAPHORE is None:
        _PDF_SEMAPHORE = asyncio.Semaphore(2)
    return _PDF_SEMAPHORE

TEMPLATES_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "templates", "contracts"))
STATIC_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "static"))
STATIC_UPLOADS_CONTRACTS_DIR = os.path.join(STATIC_DIR, "uploads", "contracts")

os.makedirs(STATIC_UPLOADS_CONTRACTS_DIR, exist_ok=True)

contract_jinja_env = Environment(loader=FileSystemLoader(TEMPLATES_DIR), autoescape=True)

DEFAULT_CONTRACT_DATA: Dict[str, Any] = {
    "contract_number": "",
    "project_address": "",
    "client_name": "",
    "contractor_name": "Rise Up Roofing and Construction, Inc.",
    "contractor_title": "Project Manager",
    "contractor_license": "1096492",
    "license_number": "1096492",
    "salesperson_name": "Marc Sarellano",
    "contract_date": "October 1, 2026",
    "contract_date_short": "Oct 1, 2026",
    "contract_title": "HOME IMPROVEMENT CONTRACT",
    "property_photo_url": "",
    "prepared_by_name": "Edith Guerrero",
    "prepared_by_title": "Project Manager",
    "scope_title": "TILE ROOF LIFT & RELAY",
    "scope_intro": "Rise Up Roofing & Construction, Inc. will complete the following roofing, preventative maintenance, exterior waterproofing, and interior repair work at the property:",
    "scope_sections": [
        {
            "heading": "Roofing Materials & Components",
            "text": "Furnish Eagle Roofing Products Bel Air concrete roof tile (or customer selected premium materials), along with all standard accessories required for a complete professional installation.",
        },
        {
            "heading": "Flashings, Metals & Penetrations",
            "text": "Furnish and install required standard galvanized/pre-painted roofing flashings, drip edge metal, pipe jacks, and counterflashings.",
        },
        {
            "heading": "Dump, Disposal & Jobsite Cleanup",
            "text": "Remove roofing debris generated by our work. Dump and disposal fees are included, followed by final daily jobsite cleanup and a magnetic sweep of all accessible ground areas.",
        },
        {
            "heading": "Underlayment & Waterproofing",
            "text": "Furnish and install new heavy-duty synthetic/modified bitumen roofing underlayment throughout the complete roof deck, including proper overlaps, valley membranes, and penetration waterproofing.",
        },
        {
            "heading": "Labor, Equipment & Project Coordination",
            "text": "Provide professional roofing labor, safety staging, standard jobsite equipment, supervision, and project coordination necessary to complete the roofing scope described above.",
        },
        {
            "heading": "Important Conditions & Decking Allowance",
            "text": "Pricing is based on the existing roof structure being in serviceable condition. Concealed structural damage, deteriorated wood, or framing repairs will be reviewed before proceeding and documented via written change order.",
        },
    ],
    "start_date": "October 16th, 2026",
    "commencement_date": "October 19th, 2026",
    "completion_date": "October 22th, 2026",
    "approx_start_date": "October 16th, 2026",
    "substantial_commencement_date": "October 19th, 2026",
    "approx_completion_date": "October 22th, 2026",
    "contract_price": "$26,870",
    "finance_charge": "N/A",
    "downpayment": "$1,000",
    "payment_schedule": [
        {
            "number": "1.",
            "description": "Initial Downpayment (Contract execution / scheduling)",
            "amount": "$1,000",
        },
        {
            "number": "2.",
            "description": "Progress Payment 1 (Teardown & delivery of materials)",
            "amount": "$7,761",
        },
        {
            "number": "3.",
            "description": "Progress Payment 2 (Underlayment & waterproofing complete)",
            "amount": "$7,761",
        },
        {
            "number": "4.",
            "description": "Final Payment (Installation complete & walkthrough)",
            "amount": "$10,348",
        },
    ],
    "payment_schedule_total": "$26,870",
    "insurance_carrier": "PACIFIC UNITED INSURANCE SERVICES",
    "insurance_phone": "(619) 274-8144",
    "workers_comp_carrier": "PACIFIC UNITED INSURANCE SERVICES",
    "workers_comp_phone": "(619) 274-8144",
    "cancellation_email": "accountant@riseuprac.com",
    "is_signed": False,
    "signed_at": "",
    "is_counter_signed": False,
    "counter_signed_at": "",
    "contractor_signature_name": "",
    "contractor_signature_data": "",
    "client_initials": "",
    "client_signature_name": "",
    "client_signature_data": "",
    "audit_trail": [],
    "cancellation_deadline": "three business days from signing",

    # Rule 11 Statutory Clauses
    "licensing_clause": "The Contractor warrants that the Contractor currently holds a valid license under the laws of the State of California to perform the work. The work performed will be done so in compliance with all applicable local, state, or federal statutes and regulations.",
    "change_order_clause": "The order must describe the scope of extra work, cost added or subtracted, and effect on progress payments or completion date prior to commencement.",
    "payment_terms_text": "Payment shall be made to the Contractor via cash, cashier’s check, or money order. Invoices are due UPON COMPLETION of each milestone phase. Accounts unpaid after 4 business days incur a $25.00 late fee or 1.5% monthly finance charge. Necessary extra materials expenses reimbursed within 2 days of receipt. Upon each payment, Contractor furnishes full and unconditional statutory lien releases pursuant to California Civil Code Sections 8400 & 8404.",
    "refund_policy_text": "Services completed and materials procured as described in this contract are not subject to refunds. The Client will not be reimbursed for services cancelled once work has begun. All sales are final upon substantial commencement.",
    "liability_insurance_text": "Rise Up Roofing and Construction, Inc. carries commercial general liability, excess umbrella, and commercial vehicle insurance written by PACIFIC UNITED INSURANCE SERVICES. You may contact them directly at (619) 274-8144 to request an official certificate of insurance.",
    "workers_comp_text": "Rise Up Roofing and Construction, Inc. carries workers’ compensation insurance for all jobsite employees and roofing crew members written by PACIFIC UNITED INSURANCE SERVICES. You may call to verify active policy status.",
    "mechanics_lien_warning_text": "Anyone who helps improve your property, but who is not paid, may record what is called a mechanics lien on your property. A mechanics lien is a claim, like a mortgage or home equity loan, made against your property and recorded with the county recorder. Even if you pay your contractor in full, unpaid subcontractors, suppliers, and laborers who helped to improve your property may record mechanics liens and sue you in court to foreclose the lien. If a court finds the lien is valid, you could be forced to pay twice or have a court officer sell your home to pay the lien. Liens can also affect your credit. BE CAREFUL. The Preliminary Notice can be sent up to 20 days after the subcontractor starts work or the supplier provides material. This can be a big problem if you pay your contractor before you have received the Preliminary Notices. PROTECT YOURSELF FROM LIENS by paying with joint checks. Visit CSLB at www.cslb.ca.gov or call 800-321-CSLB (2752). REMEMBER, IF YOU DO NOTHING, YOU RISK HAVING A LIEN PLACED ON YOUR HOME.",
    "cslb_disclosure_text": "CSLB is the state consumer protection agency that licenses and regulates construction contractors. Contact CSLB for information about the licensed contractor you are considering, including information about disclosable complaints, disciplinary actions, and civil judgments that are reported to CSLB. Use only licensed contractors. If you file a complaint against a licensed contractor within the legal deadline (usually four years), CSLB has authority to investigate the complaint.",
    "representations_text": "Each party warrants and represents that it has full authority to enter into and perform this Contract. Client Review: Client agrees to review work, be reasonably available, provide timely decisions, and ensure uninterrupted access to worksite water and electrical utilities.",
    "general_provisions_text": "Signatures: Electronic and hardcopy signatures count as legal originals for all purposes. Compliance with Laws: Contractor warrants all work complies with California Building Standards Code (Title 24) and local ordinances. Severability: Unenforceability of any term shall not impair remainder.",
    "term_termination_text": "This contract ends upon final completion and payment. If terminated earlier per contract terms, Client is responsible for paying for all work completed and material expenses incurred up to that date.",
    "bond_text": "The Client has the legal right to require the Contractor to have a performance and payment bond, the expense of which may be borne by the Client as provided by California law.",
    "three_day_notice_text": "The Client has the right to cancel this contract within three business days. You may cancel by e-mailing, mailing, faxing, or delivering a written notice to the Contractor at the Contractor’s place of business by midnight of the third business day after you receive a signed and dated copy of the contract that includes this notice. Include your name, your address, and the date you received the signed copy of the contract and this notice.",
    "five_day_notice_text": "The Client has the right to cancel this contract within five business days. You may cancel by e-mailing, mailing, faxing, or delivering a written notice to the Contractor at the Contractor’s place of business by midnight of the fifth business day after you received a signed and dated copy of the contract that includes this notice. Include your name, your address, and the date you received the signed copy of the contract and this notice.",
    "jobsite_standards_text": "Contractor warrants that all jobsite safety protocols, property protection tarps, landscape barriers, and magnetic sweeps of driveways and walkways are conducted daily. All roofing work adheres strictly to manufacturer specifications and California Building Standards Code (Title 24).",
    "decking_allowance_text": "Pricing is based on the existing roof structure being in serviceable condition. Concealed structural damage, deteriorated wood, or framing repairs will be reviewed before proceeding and documented via written change order.",
    "is_representative_signatory": False,
    "representative_name": "",
    "representative_title": "Project Manager",
}


def merge_contract_defaults(user_data: Dict[str, Any]) -> Dict[str, Any]:
    """Merge user-supplied contract data over the defaults, handling nested dicts and camelCase mapping."""
    merged = dict(DEFAULT_CONTRACT_DATA)
    if not user_data:
        return merged

    # Map frontend camelCase to snake_case if present
    camel_map = {
        "clientName": "client_name",
        "clientPhone": "client_phone",
        "clientEmail": "client_email",
        "projectAddress": "project_address",
        "contractorName": "contractor_name",
        "contractorTitle": "contractor_title",
        "contractorLicense": "contractor_license",
        "contractDate": "contract_date",
        "contractDateShort": "contract_date_short",
        "contractTitle": "contract_title",
        "propertyPhotoUrl": "property_photo_url",
        "preparedByName": "prepared_by_name",
        "preparedByTitle": "prepared_by_title",
        "scopeTitle": "scope_title",
        "scopeIntro": "scope_intro",
        "scopeSections": "scope_sections",
        "contractPrice": "contract_price",
        "downpayment": "downpayment",
        "financeCharge": "finance_charge",
        "paymentSchedule": "payment_schedule",
        "approxStartDate": "approx_start_date",
        "substantialCommencementDate": "substantial_commencement_date",
        "approxCompletionDate": "approx_completion_date",
        "cancellationEmail": "cancellation_email",
        "clientInitials": "client_initials",
        "clientSignatureName": "client_signature_name",
        "clientSignatureData": "client_signature_data",
        "contractorSignatureName": "contractor_signature_name",
        "contractorSignatureData": "contractor_signature_data",
        "licensingClause": "licensing_clause",
        "changeOrderClause": "change_order_clause",
        "paymentTermsText": "payment_terms_text",
        "refundPolicyText": "refund_policy_text",
        "liabilityInsuranceText": "liability_insurance_text",
        "workersCompText": "workers_comp_text",
        "mechanicsLienWarningText": "mechanics_lien_warning_text",
        "cslbDisclosureText": "cslb_disclosure_text",
        "representationsText": "representations_text",
        "generalProvisionsText": "general_provisions_text",
        "termTerminationText": "term_termination_text",
        "bondText": "bond_text",
        "threeDayNoticeText": "three_day_notice_text",
        "fiveDayNoticeText": "five_day_notice_text",
        "jobsiteStandardsText": "jobsite_standards_text",
        "deckingAllowanceText": "decking_allowance_text",
        "isRepresentativeSignatory": "is_representative_signatory",
        "representativeName": "representative_name",
        "representativeTitle": "representative_title",
    }

    normalized_user_data = dict(user_data)
    for c_key, s_key in camel_map.items():
        if c_key in normalized_user_data and s_key not in normalized_user_data:
            normalized_user_data[s_key] = normalized_user_data[c_key]

    for key, val in normalized_user_data.items():
        if isinstance(val, dict) and key in merged and isinstance(merged[key], dict):
            sub = dict(merged[key])
            sub.update(val)
            merged[key] = sub
        else:
            merged[key] = val

    # Format numeric amounts in payment_schedule if needed
    if isinstance(merged.get("payment_schedule"), list):
        formatted_sched = []
        for row in merged["payment_schedule"]:
            if isinstance(row, dict):
                r = dict(row)
                amt = r.get("amount")
                if isinstance(amt, (int, float)):
                    r["amount"] = f"${amt:,.0f}"
                formatted_sched.append(r)
            else:
                formatted_sched.append(row)
        merged["payment_schedule"] = formatted_sched

    # Format contract_price and downpayment if numeric
    if isinstance(merged.get("contract_price"), (int, float)):
        merged["contract_price"] = f"${merged['contract_price']:,.0f}"
    if isinstance(merged.get("downpayment"), (int, float)):
        merged["downpayment"] = f"${merged['downpayment']:,.0f}"

    return merged


def _clean_address_string(addr: str) -> str:
    if not addr:
        return ""
    parts = [p.strip() for p in str(addr).split(",") if p.strip()]
    seen = set()
    deduped = []
    for part in parts:
        lower = part.lower()
        if lower in seen:
            continue
        if lower == "ca" and any("ca" in d.lower().split() for d in deduped):
            continue
        seen.add(lower)
        deduped.append(part)
    return ", ".join(deduped)


def _render_contract_html(contract_data: Dict[str, Any]) -> str:
    """Render the contract Jinja2 template to an HTML string."""
    merged = merge_contract_defaults(contract_data)
    if not merged.get("project_address") or not str(merged["project_address"]).strip():
        merged["project_address"] = "[Project Address Pending]"
    else:
        merged["project_address"] = _clean_address_string(merged["project_address"])
    if not merged.get("client_name") or not str(merged["client_name"]).strip():
        merged["client_name"] = "[Client Name Pending]"

    # Determine execution status:
    # 1. Client signature
    is_client_signed = bool(
        merged.get("is_signed")
        or merged.get("client_signed_at")
        or merged.get("client_signature_data")
        or merged.get("signed_at")
        or merged.get("status") in ("client_signed", "signed", "fully_executed")
    )

    # 2. Company counter-signature
    is_counter_signed = bool(
        merged.get("is_counter_signed")
        or merged.get("counter_signed_at")
        or (merged.get("status") in ("signed", "fully_executed") and merged.get("counter_signed_at"))
    )

    if is_client_signed and is_counter_signed:
        execution_status_label = "FULLY EXECUTED"
        execution_status_slug = "fully-executed"
        merged["is_counter_signed"] = True
    elif is_counter_signed:
        execution_status_label = "PARTIALLY EXECUTED"
        execution_status_slug = "partially-executed"
        merged["is_counter_signed"] = True
    elif is_client_signed:
        execution_status_label = "PARTIALLY EXECUTED"
        execution_status_slug = "partially-executed"
        merged["is_counter_signed"] = False
    else:
        execution_status_label = "DRAFT"
        execution_status_slug = "draft"
        merged["is_counter_signed"] = False
        merged["is_signed"] = False

    merged["execution_status_label"] = execution_status_label
    merged["execution_status_slug"] = execution_status_slug

    template = contract_jinja_env.get_template("contract.html")
    return template.render(**merged)


def _sync_generate_contract_pdf_worker(html_content: str) -> bytes:
    """
    Renders 100% 1:1 A4 PDF using Playwright headless Chromium matching final-contract-template.html,
    executed synchronously (called via asyncio.to_thread for event-loop compatibility).
    """
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=True,
            args=["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
        )
        page = browser.new_page()
        page.set_viewport_size({"width": 794, "height": 1123})
        page.set_content(html_content, wait_until="networkidle", timeout=30000)
        try:
            page.wait_for_load_state("networkidle", timeout=10000)
            page.wait_for_function("document.fonts.ready.then(() => true)", timeout=10000)
        except Exception:
            pass
        page.wait_for_timeout(350)
        import time
        start = time.time()
        pdf_bytes = page.pdf(
            format="A4",
            print_background=True,
            margin={"top": "0mm", "right": "0mm", "bottom": "0mm", "left": "0mm"},
            prefer_css_page_size=True,
        )
        logger.critical(f"Rendered in {time.time() - start:.2f}s")
        browser.close()
        return pdf_bytes


async def generate_contract_pdf(contract_data: Dict[str, Any]) -> bytes:
    """
    Async entry-point: renders the contract template and generates a PDF via Playwright.
    Runs the blocking Playwright call in a worker thread for Windows event-loop compatibility.

    Args:
        contract_data: Dict of template variables (merged over DEFAULT_CONTRACT_DATA).

    Returns:
        PDF bytes.
    """
    html_content = _render_contract_html(contract_data)
    sem = _get_pdf_semaphore()
    async with sem:
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            _PDF_EXECUTOR,
            lambda: _sync_generate_contract_pdf_worker(html_content)
        )


async def save_contract_pdf(
    contract_data: Dict[str, Any],
    contract_id: int,
    pdf_bytes: Optional[bytes] = None
) -> str:
    """
    Generates the contract PDF (if not provided) and persists it to the static uploads directory.

    Args:
        contract_data: Template variable dict.
        contract_id: DB contract ID, used in the filename.
        pdf_bytes: Pre-generated PDF bytes to avoid redundant Chromium rendering.

    Returns:
        Public-facing relative URL, e.g. ``/static/uploads/contracts/Contract_123_20260922_141500.pdf``.
    """
    if pdf_bytes is None:
        pdf_bytes = await generate_contract_pdf(contract_data)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    contract_number = contract_data.get("contract_number", str(contract_id))
    clean_num = str(contract_number).replace("/", "_").replace("\\", "_").replace(" ", "_")
    is_signed = bool(contract_data.get("is_signed", False))
    suffix = "signed" if is_signed else "unsigned"
    filename = f"Contract_{clean_num}_{suffix}_{timestamp}.pdf"
    file_path = os.path.join(STATIC_UPLOADS_CONTRACTS_DIR, filename)
    with open(file_path, "wb") as f:
        f.write(pdf_bytes)
    return f"/static/uploads/contracts/{filename}"
