from app.core.logger import get_logger
import os
import sys
import asyncio
from typing import Dict, Any, Optional
from datetime import datetime
from jinja2 import Environment, FileSystemLoader
from concurrent.futures import ThreadPoolExecutor
from playwright.sync_api import sync_playwright

logger = get_logger(__name__)

_PDF_SEMAPHORE: Optional[asyncio.Semaphore] = None
_PDF_EXECUTOR = ThreadPoolExecutor(max_workers=2, thread_name_prefix="pdf_worker")

def _get_pdf_semaphore() -> asyncio.Semaphore:
    global _PDF_SEMAPHORE
    if _PDF_SEMAPHORE is None:
        _PDF_SEMAPHORE = asyncio.Semaphore(2)
    return _PDF_SEMAPHORE

TEMPLATES_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "templates", "contracts"))
STATIC_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "static"))
STATIC_UPLOADS_CONTRACTS_DIR = os.path.join(STATIC_DIR, "uploads", "contracts")

os.makedirs(STATIC_UPLOADS_CONTRACTS_DIR, exist_ok=True)

contract_jinja_env = Environment(loader=FileSystemLoader(TEMPLATES_DIR), autoescape=True)

DEFAULT_CONTRACT_DATA: Dict[str, Any] = {
    "contract_number": "",
    "project_address": "",
    "client_name": "",
    "contractor_name": "Edith Guerrero",
    "contractor_title": "Project Manager",
    "salesperson_name": "Marc Sarellano",
    "contract_date": "September 22, 2026",
    "contract_date_short": "Sep 22, 2026",
    "scope_title": "Complete 31-Square Concrete Tile Roof Installation",
    "scope_intro": "Rise Up Roofing & Construction, Inc. will complete the following roofing, preventative maintenance, exterior waterproofing, and interior repair work at the property:",
    "scope_sections": [
        {
            "heading": "Scope of Work — Complete Tile Roof Installation",
            "text": "Rise Up Roofing & Construction Inc. will provide all labor, roofing materials, standard equipment, supervision, and project coordination required to complete the installation of the 31-square concrete tile roofing system.",
        },
        {
            "heading": "Roofing Materials",
            "text": "Furnish Eagle Roofing Products – Bel Air 303 Sierra Madre concrete roof tile, along with the standard roofing materials required for a complete professional installation.",
        },
        {
            "heading": "Underlayment",
            "text": "Furnish and install new roofing underlayment throughout the complete roof area, including proper laps, transitions, penetrations, valleys, and critical waterproofing details.",
        },
        {
            "heading": "Flashings & Sheet Metal",
            "text": "Furnish and install required standard roofing flashings and metal components, including pipe and penetration flashings.",
        },
        {
            "heading": "Tile Installation",
            "text": "Professionally install approximately 31 squares of Eagle Bel Air 303 Sierra Madre concrete tile, including layout, alignment, fastening, cutting, and fitting at penetrations, walls, valleys, hips, and ridges.",
        },
        {
            "heading": "Hip & Ridge",
            "text": "Furnish and install matching hip and ridge tile, including transitions, fastening, and weatherproofing for a clean finished appearance.",
        },
        {
            "heading": "Labor & Equipment",
            "text": "Provide professional roofing labor, standard jobsite equipment, supervision, and project coordination necessary to complete the roofing scope described above.",
        },
        {
            "heading": "Dump, Disposal & Cleanup",
            "text": "Remove roofing debris generated by our work. Dump and disposal fees are included, followed by final jobsite cleanup and a magnetic sweep of accessible areas where appropriate.",
        },
        {
            "heading": "Important Conditions",
            "text": "Pricing is based on the existing roof structure being in serviceable condition. Concealed structural damage, deteriorated wood, framing repairs, engineering, permit fees, or other additional work are not included unless specifically stated in writing. Any additional work discovered after the project begins will be reviewed with the owner before proceeding and documented through a written change order.",
        },
    ],
    "start_date": "October 16th, 2026",
    "commencement_date": "October 19th, 2026",
    "completion_date": "October 22th, 2026",
    "contract_price": "$31,000.00",
    "finance_charge": "N/A",
    "downpayment": "$1,000.00",
    "payment_schedule": [
        {
            "number": "1.",
            "description": "Initial Payment (Contract execution / project scheduling / material coordination)",
            "amount": "$1,000.00",
        },
        {
            "number": "2.",
            "description": "Progress Payment (Start of roofing work / initial installation stage)",
            "amount": "$9,300.00",
        },
        {
            "number": "3.",
            "description": "Progress Payment (Underlayment, waterproofing & flashing stage completed)",
            "amount": "$9,300.00",
        },
        {
            "number": "4.",
            "description": "Final Payment (Project completion and final walkthrough)",
            "amount": "$11,400.00",
        },
    ],
    "payment_schedule_total": "$31,000.00",
    "license_number": "#1096492",
    "insurance_carrier": "PACIFIC UNITED INSURANCE SERVICES",
    "insurance_phone": "(619) 274-8144",
    "workers_comp_carrier": "PACIFIC UNITED INSURANCE SERVICES",
    "cancellation_email": "accountant@riseuprac.com",
    "is_signed": False,
    "signed_at": "",
    "is_counter_signed": False,
    "counter_signed_at": "",
    "contractor_signature_name": "",
    "contractor_signature_data": "",
    "client_initials": "",
    "client_signature_name": "",
    "client_signature_data": "",
    "audit_trail": [],
    "cancellation_deadline": "three business days from signing",
}


def merge_contract_defaults(user_data: Dict[str, Any]) -> Dict[str, Any]:
    """Merge user-supplied contract data over the defaults, handling nested dicts."""
    merged = dict(DEFAULT_CONTRACT_DATA)
    if not user_data:
        return merged
    for key, val in user_data.items():
        if isinstance(val, dict) and key in merged and isinstance(merged[key], dict):
            sub = dict(merged[key])
            sub.update(val)
            merged[key] = sub
        else:
            merged[key] = val
    return merged


def _render_contract_html(contract_data: Dict[str, Any]) -> str:
    """Render the contract Jinja2 template to an HTML string."""
    merged = merge_contract_defaults(contract_data)
    if not merged.get("project_address") or not str(merged["project_address"]).strip():
        merged["project_address"] = "[Project Address Pending]"
    if not merged.get("client_name") or not str(merged["client_name"]).strip():
        merged["client_name"] = "[Client Name Pending]"

    # Determine execution status:
    # 1. Client signature
    is_client_signed = bool(
        merged.get("is_signed")
        or merged.get("client_signed_at")
        or merged.get("client_signature_data")
        or merged.get("signed_at")
        or merged.get("status") in ("client_signed", "signed", "fully_executed")
    )

    # 2. Company counter-signature
    is_counter_signed = bool(
        merged.get("is_counter_signed")
        or merged.get("counter_signed_at")
        or (merged.get("status") in ("signed", "fully_executed") and merged.get("counter_signed_at"))
    )

    if is_client_signed and is_counter_signed:
        execution_status_label = "FULLY EXECUTED"
        execution_status_slug = "fully-executed"
        merged["is_counter_signed"] = True
    elif is_client_signed:
        execution_status_label = "PARTIALLY EXECUTED"
        execution_status_slug = "partially-executed"
        merged["is_counter_signed"] = False
    else:
        execution_status_label = "DRAFT"
        execution_status_slug = "draft"
        merged["is_counter_signed"] = False
        merged["is_signed"] = False

    merged["execution_status_label"] = execution_status_label
    merged["execution_status_slug"] = execution_status_slug

    template = contract_jinja_env.get_template("contract.html")
    return template.render(**merged)


def _sync_generate_contract_pdf_worker(html_content: str) -> bytes:
    """
    Renders high-fidelity Letter PDF using Playwright headless Chromium,
    executed synchronously (called via asyncio.to_thread for event-loop compatibility).
    """
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=True,
            args=["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
        )
        page = browser.new_page()
        page.set_viewport_size({"width": 816, "height": 1056})
        page.set_content(html_content, wait_until="networkidle", timeout=30000)
        try:
            page.wait_for_load_state("networkidle", timeout=10000)
            page.wait_for_function("document.fonts.ready.then(() => true)", timeout=10000)
        except Exception:
            pass
        page.wait_for_timeout(350)
        import time
        start = time.time()
        pdf_bytes = page.pdf(
            format="Letter",
            print_background=True,
            margin={"top": "0mm", "right": "0mm", "bottom": "0mm", "left": "0mm"},
            prefer_css_page_size=True,
        )
        logger.critical(f"Rendered in {time.time() - start:.2f}s")
        browser.close()
        return pdf_bytes


async def generate_contract_pdf(contract_data: Dict[str, Any]) -> bytes:
    """
    Async entry-point: renders the contract template and generates a PDF via Playwright.
    Runs the blocking Playwright call in a worker thread for Windows event-loop compatibility.

    Args:
        contract_data: Dict of template variables (merged over DEFAULT_CONTRACT_DATA).

    Returns:
        PDF bytes.
    """
    html_content = _render_contract_html(contract_data)
    sem = _get_pdf_semaphore()
    async with sem:
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            _PDF_EXECUTOR,
            lambda: _sync_generate_contract_pdf_worker(html_content)
        )


async def save_contract_pdf(
    contract_data: Dict[str, Any],
    contract_id: int,
    pdf_bytes: Optional[bytes] = None
) -> str:
    """
    Generates the contract PDF (if not provided) and persists it to the static uploads directory.

    Args:
        contract_data: Template variable dict.
        contract_id: DB contract ID, used in the filename.
        pdf_bytes: Pre-generated PDF bytes to avoid redundant Chromium rendering.

    Returns:
        Public-facing relative URL, e.g. ``/static/uploads/contracts/Contract_123_20260922_141500.pdf``.
    """
    if pdf_bytes is None:
        pdf_bytes = await generate_contract_pdf(contract_data)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    contract_number = contract_data.get("contract_number", str(contract_id))
    clean_num = str(contract_number).replace("/", "_").replace("\\", "_").replace(" ", "_")
    is_signed = bool(contract_data.get("is_signed", False))
    suffix = "signed" if is_signed else "unsigned"
    filename = f"Contract_{clean_num}_{suffix}_{timestamp}.pdf"
    file_path = os.path.join(STATIC_UPLOADS_CONTRACTS_DIR, filename)
    with open(file_path, "wb") as f:
        f.write(pdf_bytes)
    return f"/static/uploads/contracts/{filename}"
